app = "kpiwa-wpp"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # The *only* health check the edge should use
  [[http_service.checks]]
    type = "http"
    method = "GET"
    path = "/health"
    interval = "10s"
    timeout = "7s"
    grace_period = "120s"

  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 400

[[mounts]]
  source = "kpiwa_data"
  destination = "/app/data"

[[vm]]
  memory = "6gb"
  cpu_kind = "performance"
  cpus = 2

[deploy]
  # prefer rolling so your single volume machine isn't taken down first
  strategy = "rolling"
  # optional; if you really need a release step, keep it—but it runs in a throwaway VM
  # release_command = "npm ci --only=production"
